---
- name: initial_setup
  hosts: localhost
  become: yes  # Run with sudo privileges
  
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install required packages
      apt:
        name:
          - chrony
          - git
          - kea
          - bind9
        state: present

    - name: download chrony configuration file
      get_url:
        url: https://raw.githubusercontent.com/ftflstwd/netnexus/main/assets/cloud-init/chrony/chrony.conf
        dest: /etc/chrony/chrony.conf
        mode: '0644'
        owner: root
        group: root

    - name: ensure chrony service is running and enabled
      service:
        name: chrony
        state: restarted
        enabled: yes
