---
- name: install docker
  hosts: localhost
  become: yes

  tasks:
    - name: update the apt package index
      apt:
        update_cache: yes

    - name: install packages to allow apt to use a repository over HTTPS
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: add docker's official gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository
      apt_repository:
        repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu noble stable
        state: present

    - name: update the apt package index again
      apt:
        update_cache: yes

    - name: install the latest version of Docker
      apt:
        name: docker-ce
        state: latest
        
    - name: ensure docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes
        
- name: deploy the docker_chrony container
  hosts: localhost  
  become: yes  
  tasks:

#    - name: Log in to GitHub Container Registry (if the image is private)
#      community.docker.docker_login:
#        registry_url: https://ghcr.io
#        username: "{{ ghcr_username | default(omit) }}"  # Provide your GitHub username
#        password: "{{ ghcr_password | default(omit) }}"  # Provide your GitHub token/password
#      when: ghcr_username is defined and ghcr_password is defined

    - name: pull the docker_chrony image
      community.docker.docker_image_pull:
        name: ghcr.io/ftflstwd/docker_chrony:main
        tag: "main"
      register: pull_result
      retries: 3
      delay: 10
      until: pull_result is success

    - name: deploy the docker_chrony container
      community.docker.docker_container:
        name: chrony
        image: "ghcr.io/ftflstwd/docker_chrony:main"
        state: started
        restart_policy: unless-stopped
      register: container_result
      retries: 3
      delay: 10
