---
- name: initial_setup
  hosts: localhost
  become: yes  # Run with sudo privileges
  
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: install required packages
      apt:
        name:
          - chrony
          - kea
          - bind9
        state: present
